#!/bin/bash

# Git log format with merge commit highlighting
# Used by git aliases: l, ls, lg, lp

FORMAT="%C(yellow)%h %Cgreen%ad %Cblue%<(12,trunc)%aN%Creset%C(red)%d%Creset %s"

function pretty_git_log {
    cd -- ${GIT_PREFIX:-.}
    git log --color --date=short --abbrev=10 --pretty="format:${FORMAT}" "$@" |
    # Highlight merge commits in magenta
    sed -Ee "s/(Merge .*$)/\x1b[35m\1\x1b[0m/" |
    # Page only if needed
    less -FXRS
}

