= Guide on Setting Up Development Environment
:toc:
:numbered:

This guide is written to help me setup new Windows and Mac machines.

== Windows

=== Prerequisites

==== Windows Installer Flash Drive

. Use https://rufus.akeo.ie/[Rufus] to create bootable USB.
.  Use `en_windows_10_multiple_editions_version_1511_x64_dvd_7223712.iso`

==== Windows 10 Anniversary Update

Make sure you have Windows 10 Anniversary Update available for offline installation.

==== Drivers

For installing Windows on Macbook Pro, you need to download Bootcamp.

. Clone https://github.com/timsutton/brigadier[Brigadier]

    git clone --depth 1  https://github.com/timsutton/brigadier.git

. Use http://www.everymac.com/ultimate-mac-lookup/[EveryMac] online tool to find your Macbook
model identifier using serial number
. Download Bootcamp

    mkdir MacbookPro10-1
    ./brigadier -m MacBookPro10,1 -o MacBookPro10-1

=== Install Windows 10

Install a fresh copy of Windows 10. Make sure you do not enable network connection during or after
installation until drivers have been installed.

. Select custom settings and disable all settings related to Cortana etc
. Attach flash drive with Windows 10 Anniversary Update iso and install update 
from it
. Again disable all Cortana related options in settings
. Attach flash drive with Bootcamp on it, click on __Setup.exe__ to start driver installation
. Restart machine

==== Configure Bootcamp

. Under __Keyboard__, enable __Use all F1, F2...__ option
. Under __Trackpad__, enable __Tap To Click__ and __Secondary __Tap__ 

==== Change Computer Name

. Open __Advanced System Settings__ using

    rundll32.exe shell32.dll,Control_RunDLL sysdm.cpl,,1

. Click on __Change__ button
. Rename

Now restart machine and connect to internet.

=== Post Installation Configuration

==== Set Time

. Open time and date settings using

    control timedate.cpl

. Set time zone
. Use 24 hour time format

==== Map Keys

NOTE: My Windows machine is a Macbook. Left Win is actually Left Cmd key
which is right next to the space bar.

Use SharpKeys to,

. Map Caps Lock to Left Ctrl key
. Map Left Ctrl to Left Win key
. Map Left Win to Right Ctrl key

==== Track Pad

To invert the direction of scrolling (natural scrolling on macOS), run following command in PowerShell with administrative privileges.

```powershell
Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Enum\HID\__\__\Device` Parameters FlipFlopWheel -EA 0 | ForEach-Object { Set-ItemProperty $_.PSPath FlipFlopWheel 1 }
Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Enum\HID\__\__\Device` Parameters FlipFlopHScroll  -EA 0 | ForEach-Object { Set-ItemProperty $_.PSPath FlipFlopHScroll 1 }

```

See http://superuser.com/a/364353/42415[SuperUser answer] for details.

Natural direction of scrolling is how you scroll on iPhone, Android and
 other touch devices. Content scrolls in the direction of your fingers.

==== Mouse Properties

Open mouse properties using `control main.cpl`.

. In __Buttons__ tab, turn on __ClickLock__
.. In __Settings__, set duration to the shortest possible
. In __Pointer Options__ tab, enable __Show Location of Pointer__
. In __Wheel__ tab, change scroll speed to 1

=== Install Applications using `Scoop`

Install http://scoop.sh/[Scoop].

[source, powershell]
----
iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
----

Use `scoop install` to install following applications,

. ag
. curl
. git
. llvm
. lua
. openssh
. ruby
. vim
. wget
. yarn
. youtube-dl

==== Scoop Extras

Add `scoop` "extras" bucket.

----
scoop bucket add extras
---- 

Then install following applications,

. atom
. conemu
. sharex
. SumatraPdf
. vccode

=== Configure Applications Post Install

==== Add ConEmu to context menu

. Open __Settings__ -> __Integration__
. Click on __Register__ to add ConEmu to context menu

==== Configure SSH keys for Git

.Generate SSH Keys

After installing `git` and `openssh`, run `ssh-keygen` command in Powershell.

[source, powershell]
----
PS> ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/c/Users/you//.ssh/id_rsa): [press enter]
Enter passphrase (empty for no passphrase): [type your password]
Enter same passphrase again: [and once more]
...
----

https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/[Add
 new SSH key to Github account].

.Use Pshazz to remember SSH password

Pshazz includes a plugin for SSH that can save your SSH key password in
Windows Credential Manager so you don't need to re-type it every time you
push to your Github repo. Install it like this:

----
scoop install pshazz
----

You should see a popup asking for your SSH key password. Enter it and check
the box to save your password. Back in your Powershell session, you should
see an Identity Added message. 
 
Whenever you start a Powershell session from
now on, Pshazz will make sure the ssh-agent is running and load your private
key using your saved password

.Test SSH connection

To make sure everything's working, restart Powershell and then run this
command

----
ssh -T git@github.com
----

After a warning or two, you should see a message like this:

----
Hi <username>! You've successfully authenticated, but GitHub does not provide shell access. 
----

https://help.github.com/articles/testing-your-ssh-connection/[Visit Github help]
for details.

=== Install Applications

. https://github.com/canton7/SyncTrayzor[SyncTazor]
.. Setup sync with other computers
. https://1password.com/downloads/[1Password]
. https://www.mozilla.org/en-US/firefox/developer/[Firefox Developer Edition]
.. Enable Firefox sync
.. Login to RescueTime plugin
.. Configure Pray Times plugin
.. Install https://agilebits.com/onepassword/extensions[1Password extension]
. https://www.rescuetime.com/get_rescuetime[RescueTime]
. https://mridgers.github.io/clink/[Clink].
. http://www.revouninstaller.com/download-freeware-version.php[Revo Uninstaller Freeware]
. https://sharpkeys.codeplex.com/[SharpKeys]
. https://git-for-windows.github.io/[Git for Windows]
. Setup https://download.qt.io/archive/qt/[Qt]
.. https://www.qt.io/download-open-source/#section-9[Latest Qt Creator]
.. https://download.qt.io/archive/qt/5.5/5.5.1/[Qt `5.5.1` for Windows 32bit VS 2013]
.. CDB debugger for Qt
... Download
 https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk[Windows
 10 SDK online installer]. Offline installer is
 http://superuser.com/a/1020752/42415[not available]
... Either install it directly or choose to download only
... Installer will present a menu of features. Select __Debugging Tools for Windows__ (~100MB)
... Install it manually from download folder, if you had opted for download option
. Visual Studio 2013
. https://slproweb.com/products/Win32OpenSSL.html[Win32 OpenSSL 1.0.1 Light] into Windows System folders
. https://zealdocs.org/[ZealDocs]
.. Download Qt5 documentation
.. Download C++ documentation
. https://autohotkey.com/[AutoHotKey]
. http://www.7-zip.org/download.html[7-Zip]
. https://code.visualstudio.com/[Visual Studio Code]
.. https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync[Visual Studio Code Settings Sync Extension]
.. Download Visual Studio Code settings using Gist ID and Personal Access
 Token stored in 1Password
. Install https://www.python.org/downloads/windows/[Python2 and Python3]
. Install https://rubyinstaller.org/[Ruby]
. Install https://evernote.com/download/get.php?file=Win[Evernote]
. Install https://hluk.github.io/CopyQ/[CopyQ Clipboard Manager]
. Install http://rambox.pro/[Rambox] 
.. Enable and Setup
... Slack
... Inbox (Personal)
... Inbox (Work)
... Gmail (University)
... WhatsApp
... Telegram
... IRC Cloud
.. Setup https://github.com/saenzramiro/rambox/wiki/Inject-JavaScript-Code[auto reload for Slack]
.. Setup Google Calendar
... Url: http://google.com/calendar
... Logo: https://i.imgur.com/taT0Yxn.png
.. Setup Google Spreadsheets
... Url: https://docs.google.com/spreadsheets
... Logo: https://i.imgur.com/Ny6YHlK.png 
. MS Office
. https://www.sumatrapdfreader.org/free-pdf-reader.html[Sumatra PDF]
. https://www.dropbox.com/install[Dropbox]
. Install Chocolatey Packages
.. Install https://chocolatey.org/install[Chocolatey]

=== Fonts

. Install https://github.com/google/fonts/tree/master/ofl/inconsolata[Inconsolata fonts]

=== Download Portable Applications

Create a folder `bin` in `%HOMEPATH%`,

----
mkdir %HOMEPATH%\bin
----

This folder is referred to as `bin` henceforth.

Download following apps and extract them in `bin` folder,

 . https://tuxproject.de/projects/vim/[Vim] 
 . http://luabinaries.sourceforge.net/[Lua] 
 .. Navigate and download from `Windows Libraries/Dynamic` folder
. http://www.softwareok.com/?Download=DontSleep[Don't Sleep Utility]
.. Set __Options__ to __Start Minimized__ and __Start with Windows__
. http://www.majorgeeks.com/files/details/windows_update_minitool.html[Windows Update MiniTool]

Add their path to `%PATH%` variable.

To edit `%PATH%` variable, open Environment Variables using 
 
----
rundll32.exe shell32.dll,Control_RunDLL sysdm.cpl,,3
----

You can check path of each command using `where` command. For example,

----
> where gvim C:\Users\talha\bin\complete-x64\gvim.exe 
----

You can use it to test each downloaded program is available from `%PATH%`.

=== Dotfiles

Create a `Repos` directory in `%HOMEPATH%`. Clone https://github.com/talha131/dotfiles[dotfiles repository].

     git clone https://github.com/talha131/dotfiles.git

==== Git

Start a `cmd` tab with administrative privilege in ConEmu. Create symbolic links thusly,

----
mklink %HOMEPATH%\.gitconfig %HOMEPATH%\Repos\dotfiles\git\gitconfig
mklink %HOMEPATH%\.githelper %HOMEPATH%\Repos\dotfiles\git\githelper
mklink %HOMEPATH%\bin\diff-highlight %HOMEPATH%\Repos\dotfiles\bin\diff-highlight
----

==== Vim

Open Vim and check you have Python2, Python3, Ruby, and Lua working, using following commands,

----
:echo has('python3')
:echo has('python')
:echo has('ruby')
:echo has('lua')
----

===== Link to Vim Configuration

Start `cmd` with administrative privilege in ConEmu. Create symbolic links thusly,

----
mklink %HOMEPATH%\.vimrc %HOMEPATH%\Repos\dotfiles\vim\vimrc
mklink /d %HOMEPATH%\.vim\ %HOMEPATH%\Repos\dotfiles\vim\vim\
----

===== Install Vim-Plug

I use https://github.com/junegunn/vim-plug[Vim-Plug] to manage my Vim
plugins. https://github.com/junegunn/vim-plug#installation[To install Vim-Plug],
open Powershell and type these commands,

[source,powershell]
----
md ~\.vim\autoload
$uri = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
(New-Object Net.WebClient).DownloadFile($uri, $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath("~\.vim\autoload\plug.vim"))
----

===== Install Plugins

Open Vim, ignore errors and issue `:PlugInstall!` to install all plugins and
 themes.

Restart Vim. This time there should be no errors.

===== Add gVim to Context Menu

Portable version of Vim from Tuxproject which does not come with an
 installer. It is not automatically added to the Windows context.

To add gVim to context menu, open registry using `regedit`.

. Navigate to `HKEY_CLASSES_ROOT\*\shell`.
. Add new key `gVim` under it.
. Change value of `Default` to `Open with gVim`
. Add a new string value, named `Icon`. Set it's value to gVim executable,
in this case `"C:\Users\talha\bin\complete-x64\gvim.exe"`
. Add a new sub key under `gVim`. Name it `command`
. Set `command`'s default value to gVim executable, in this case
 `"C:\Users\talha\bin\complete-x64\gvim.exe" "%1"`

See http://superuser.com/a/37923/42415[this link] for details.

==== AutoHotKey

To auto start the AutoHotKey script every time windows starts. Start `cmd`
 with administrative privilege in ConEmu. Create symbolic links thusly,

```powershell
mklink "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\init.ahk" %HOMEPATH%\Repos\dotfiles\autohotkey\init.ahk
```

==== Install AutoJump

You must have Clink installed before you install AutoJump

. Clone https://github.com/wting/autojump[AutoJump]
. Add https://github.com/wting/autojump/issues/436[patch]
. Open `cmd`
. Make sure Clink is working in `cmd`
. Switch to AutoJump directory
. Install AutoJump using `python install.py`
. Successful installation will output a path, add this path your `%PATH%`.

==== Clink

You can view Clink settings and configuration directory using `clink set` command.

=== Color Codes

To have https://github.com/morhetz/gruvbox[Gruvbox] dark theme like background in `cmd` or Git shell, use following color codes:

.Color Codes
[cols="4", options="header"]
|===
|Color Values
|Red
|Green
|Blue

|Screen Background,
|44
|44
|44

|Screen Text
|218
|198
|144
|===

=== Urdu Support

. Add Urdu language support to Windows 10
. Install https://urdu.ca/2[Phonetic Keyboard]
. Install fonts
    . http://font.urduweb.org/downloads/357-decotype-naskh-regular[DecoType Naskh Regular]
    . http://font.urduweb.org/downloads/363-diwani-letter-regular[Diwani Letter Regular]
    . http://font.urduweb.org/downloads/243-khat-e-sulas-regular[Khat-e-Sulas Regular]
    . http://font.urduweb.org/downloads/244-khat-e-sulas-shipped-regular[Khat-e-Sulas Shipped Regular]
    . http://font.urduweb.org/downloads/376-old-antic-bold-regular[Old Antic Bold Regular]
    . http://www.noorehidayat.org/index.php?p=cnt&c=noorehuda.ttf[NooreHuda]
    . http://font.urduweb.org/downloads/249-jameel-noori-nastaleeq-regular[Jameel Noori Nastaleeq Regular]
    . https://brushez.com/free_download/10eoM/39610[FS Diwani]

=== Deprecated Notes

Notes under this section are currently not in use. I keep them around for probable
future use.

==== [line-through]#Disable Automatic Updates#

WARNING: This section may not be relevant after Windows 10 anniversary
 update. I did not face issue with Windows update after anniversary update.

Windows 10 automatic updates messed up device drivers, rendering my machine
 unstable. I had to reinstall Windows 10 at least 10 times before learning my
 lesson to not to trust Windows 10 automatic updates.

.Disable Windows Update Service

. Open `services.msc`
. Stop and disable __Windows Update Service__

.Disable Windows Driver Update

. Open driver update setting, using

    rundll32.exe shell32.dll,Control_RunDLL sysdm.cpl,,2

. Click on __Device Installation Settings__ and disable drivers updates

Help article on https://support.microsoft.com/en-us/kb/3073930[How to
 temporarily prevent a driver update from reinstalling in Windows 10] may be
 useful, though it didn't do much for me.

.Edit Group Policy

. Open `gpedit.msc`
. __Computer Configuration__ -> __Administrative Templates__ -> __Windows Components__
-> __Windows Update__ -> __Configure Automatic Updates__
. Enable __Configure Automatic Updates__
. Choose __Notify to download and notify to install__

.Update Windows Manually

Install
 http://www.majorgeeks.com/files/details/windows_update_minitool.html[Windows
 Update MiniTool] and use it to update Windows manually.

==== [line-through]#Install Applications#

WARNING: Following applications have been replaced by their alternatives or `scoop`
manages them.

. https://conemu.github.io/en/[ConEmu Windows Terminal]

==== [line-through]#diff.exe for Vim#

IMPORTANT: Tuxproject Vim does not include a `diff.exe`.
`diff` or `Gdiff` (in Vim Fugitive) may not work.
On the other hand, https://github.com/vim/vim-win32-installer[Vim Win32
Installer] is shipped with `diff`.

Check output of

----
:!where diff
----

If the result is empty or `Gdiff` is not working then add `diff.exe` from Git
 installation to your `%PATH%`.

Open your Environment Variables, edit `%PATH%` to add `C:\Program
 Files\Git\usr\bin`.

See this
 https://github.com/tpope/vim-fugitive/issues/680#issuecomment-134650380[Github
 issue] for details.

== Outdated Content

CAUTION: I need to review and update following portion of this file.

=== Overview of my dotfiles


These configuration files do not work out of the box. These are specific to my Mac OSX system.

Following are my not so comprehensive and perhaps out of date notes.

=== Git


. http://dropshado.ws/post/7844857440/gitconfig-colors[David DeSandro] blog entry is a good start point.
. http://cheat.errtheblog.com/s/git[Cheat sheets] has more comprehensive entry.

=== Vim

. https://chrome.google.com/webstore/detail/godjoomfiimiddapohpmfklhgmbfffjj[Vrome] is a Google Chrome extension.

==== Auto Close

. http://stackoverflow.com/q/883437/177116[SO thread] has got some good comments.
. I decided to use Thiago Alves/Townk's https://github.com/Townk/vim-autoclose[plugin].
. http://www.vim.org/scripts/script.php?script_id=2009[Townk's plugin tutorial].

==== Vim Markdown

. https://github.com/tpope/vim-markdown[tpope/vim-markdown] is mostly used. But it does not conceal text markers in Markdown file.
. https://github.com/xolox/vim-markdown[xolox/vim-markdown] does the concealing. See https://github.com/tpope/vim-markdown/pull/9#issuecomment-3098050[this image] for example.
. But you have to switch to xolox/vim-markdown `conceal` branch to get his code. Use `git checkout -b conceal remotes/origin/conceal` to
    checkout the branch.

==== Fuzzy File Finder

. I tried https://wincent.com/products/command-t/[command-t] but I could not make it work. It requires that your copy of Vim should be compiled with the same version of ruby with which you compiled command-t, which effectively means you have to compile Vim yourself.
. I took the easier way, use http://kien.github.com/ctrlp.vim/[CtrlP]. It is basically the same as Command-T but written in pure Vimscript. This means it neither requires Ruby support enabled in Vim nor does it require the compilation of some Ruby extension implemented in C.
. Other extensions are either not what I wanted, for example, http://www.vim.org/scripts/script.php?script_id%3D2050[LustyJuggler], or not actively maintained any more like http://www.vim.org/scripts/script.php?script_id%3D1984[FuzzyFinder] and https://github.com/jamis/fuzzy_file_finder[fuzzy file finder].

=== Bash

. Bash completion depends on bash\_completion package. MacPorts users can do `sudo port install git-core +bash_completion`.
. http://blog.bitfluent.com/post/27983389/git-utilities-you-cant-live-without[Git Utilities You Can't Live Without] blog entry has an entry for Git aware PS1.
