= Guide on Setting Up Development Environment
:toc:
:numbered:

This is a brief guide I wrote and keep updated for my benefit.
It servers me any time I have to setup a new Windows or Mac machine for personal use.

== Windows

Install a fresh copy of Windows 10. Then follow these steps.

=== Change Computer Name

. Open __Advanced System Settings__ using

    rundll32.exe shell32.dll,Control_RunDLL sysdm.cpl,,1

. Click on __Change__ button
. Rename

=== Set Time

. Open time and date settings using

    control timedate.cpl

. Set time zone
. Use 24 hour time format

=== Disable Automatic Updates

WARNING: This section may not be relevant after Windows 10 anniversary update

Windows 10 automatic updates mess up with drivers, rendering my machine unstable. I had to reinstall Windows 10 at least 10 times before learning my lesson to never to trust Windows 10 automatic updates.

.Disable Windows Update Service

. Open `services.msc`
. Stop and disable __Windows Update Service__

.Disable Windows Driver Update

. Open driver update setting, using
    rundll32.exe shell32.dll,Control_RunDLL sysdm.cpl,,2
. Click on __Device Installation Settings__ and disable drivers updates

.Edit Group Policy

. Open `gpedit.msc`+
  __Computer Configuration__ -> __Administrative Templates__ -> __Windows Components__ -> __Windows Update__ -> __Configure Automatic Updates__
. Enable it
. Choose __Notify to download and notify to install__

. Download Windows Update Manually

Update Windows Defender manually. Later use __Windows Update MiniTool__ for installing selective updates.

Also download https://support.microsoft.com/en-us/kb/3073930[this tool] from Microsoft support website. It hasn't been of any use at the time of writing but just keep it in case it may prove useful.

=== Install Applications

. Install http://www.majorgeeks.com/files/details/windows_update_minitool.html[Windows Update MiniTool]
. Install https://github.com/canton7/SyncTrayzor[SyncTazor]
.. Sync with other computers
. Install https://1password.com/downloads/[1Password]
. Install https://www.mozilla.org/en-US/firefox/developer/[Firefox Developer Edition]
.. Enable Firefox sync
.. Login to RescueTime plugin
.. Configure Pray Times plugin
.. Install https://agilebits.com/onepassword/extensions[1Password extension]
. Install https://www.rescuetime.com/get_rescuetime[RescueTime]
. Install https://conemu.github.io/en/[ConEmu Windows Terminal]
.. Open __Settings__ -> __Integration__. Click on __Register__ to add ConEmu to context menu
. Install https://mridgers.github.io/clink/[Clink].
. Install http://www.revouninstaller.com/download-freeware-version.php[Revo Uninstaller Freeware]
. Install https://sharpkeys.codeplex.com/[SharpKeys]
. Install https://git-for-windows.github.io/[Git for Windows]
. Setup https://download.qt.io/archive/qt/[Qt]
.. Install https://www.qt.io/download-open-source/#section-9[Latest Qt Creator]
.. Install (https://download.qt.io/archive/qt/5.5/5.5.1/)[Qt `5.5.1` for Windows 32bit VS 2013]
. Install CDB debugger for Qt
.. Download https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk[Windows 10 SDK online installer]. Offline installer is http://superuser.com/a/1020752/42415[not available]
.. Either install it directly or choose to download only
.. Installer will present a menu of features. Select __Debugging Tools for Windows__ (~100MB)
.. Install it manually from download folder, if you had opted for download option
. Install Visual Studio 2013
. Install https://slproweb.com/products/Win32OpenSSL.html[Win32 OpenSSL `1.0.1` Light] into Windows System folders
. Install (https://zealdocs.org/
)
.. Download Qt5 documentation
.. Download C++ documentation
. Install https://autohotkey.com/[AutoHotKey]
. Install http://www.7-zip.org/download.html[7-Zip]
. Install https://slack.com/downloads[Slack]
. Install Chocolatey Packages
.. Install https://chocolatey.org/install[Chocolatey]
.. Install https://github.com/ggreer/the_silver_searcher/wiki/Windows[Ag - The Silver Searcher]
. Install https://www.python.org/downloads/windows/[Python2 and Python3]
. Install https://rubyinstaller.org/[Ruby]
. https://code.visualstudio.com/[Visual Studio Code]
.. Install https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync[Visual Studio Code Settings Sync]
.. Download Visual Studio Code settings
. Install https://github.com/google/fonts/tree/master/ofl/inconsolata[Inconsolata fonts]
. Install https://evernote.com/download/get.php?file=Win[Evernote]
. Install https://hluk.github.io/CopyQ/[CopyQ Clipboard Manager]
. Install http://www.softwareok.com/?Download=DontSleep[Don't Sleep Utility]
.. Alternate is http://desmondbrand.com/caffeinated/[Caffeinated] but it requires .Net 3.5
.. Another alternate is http://www.zhornsoftware.co.uk/caffeine/[Caffeine] but it http://vi.stackexchange.com/questions/3342/using-vim-and-caffeine-on-the-same-machine[keeps inserting `<F15>` in Vim]
.. Set options in Don't Sleep to Start Minimized and Start with Windows
. Install http://meetfranz.com/[Franz]
.. Clone https://github.com/talha131/plugins.git[fork of plugins repository]
.. Paste plugins
... Google Calendar
... Google Spreadsheets
... Facebook
.. Setup
... Inbox for personal email
... Inbox for office email
... Personal Google Calendar
... Google Spreadsheets
... WhatsApp
... Telegram
... IRC Cloud

=== Download Applications

Create a folder `bin` in `%HOMEPATH%`, using `mkdir %HOMEPATH%\bin` command. This folder is referred to as `bin`, henceforth.

Download following apps and extract them in `bin` folder, and add their path to `%PATH%` variable.

To edit `%PATH%` variable, open Environment Variables using `rundll32.exe shell32.dll,Control_RunDLL sysdm.cpl,,3`.

1. https://tuxproject.de/projects/vim/[Vim]
1. http://luabinaries.sourceforge.net/[Lua]
	1. Navigate and download from `Windows Libraries/Dynamic` folder

You can check path of each command using `where` command. For example,

```
> where gvim
C:\Users\talha\bin\complete-x64\gvim.exe
```

You can use it to test each downloaded program is available from `%PATH%`.

=== Configure

===== Map Keys

Use SharpKeys to,

1. Map Caps Lock to Left Ctrl key
1. Map Left Ctrl to Left Win key
1. Map Left Win to Right Ctrl key

===== Track Pad

To invert the direction of scrolling (natural scrolling on macOS), run following command in PowerShell with administrative privileges.

```powershell
Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Enum\HID\__\__\Device` Parameters FlipFlopWheel -EA 0 | ForEach-Object { Set-ItemProperty $_.PSPath FlipFlopWheel 1 }
Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Enum\HID\__\__\Device` Parameters FlipFlopHScroll  -EA 0 | ForEach-Object { Set-ItemProperty $_.PSPath FlipFlopHScroll 1 }

```

See http://superuser.com/a/364353/42415[SuperUser answer] for details.

Natural direction of scrolling is how you scroll on iPhone, Android and other touch devices. Content scrolls in the direction of your fingers.

===== Mouse Properties

Open mouse properties using `control main.cpl`.

. In __Buttons__ tab, turn on __ClickLock__
.. In __Settings__, set duration to the shortest possible
. In __Pointer Options__ tab, enable __Show Location of Pointer__
. In __Wheel__ tab, change scroll speed to 1

=== Dotfiles

Create a `Repos` directory in `%HOMEPATH%`. Clone https://github.com/talha131/dotfiles[dotfiles repository].

===== Git

Start a `cmd` tab with administrative privilege in ConEmu. Create symbolic links thusly,

----
mklink %HOMEPATH%\.gitconfig %HOMEPATH%\Repos\dotfiles\git\gitconfig
mklink %HOMEPATH%\.githelper %HOMEPATH%\Repos\dotfiles\git\githelper
mklink %HOMEPATH%\bin\diff-highlight %HOMEPATH%\Repos\dotfiles\bin\diff-highlight
----

===== Vim

Open Vim and check you have Python2, Python3, Ruby, and Lua working, using following commands,

----
:echo has('python3')
:echo has('python')
:echo has('ruby')
:echo has('lua')
----

.Link to Vim Configuration

Start `cmd` with administrative privilege in ConEmu. Create symbolic links thusly,

----
mklink %HOMEPATH%\.vimrc %HOMEPATH%\Repos\dotfiles\vim\vimrc
mklink /d %HOMEPATH%\.vim\ %HOMEPATH%\Repos\dotfiles\vim\vim\
----

.Install Vim-Plug

Open Powershell and type these commands

[source,powershell]
----
md ~\.vim\autoload
$uri = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
(New-Object Net.WebClient).DownloadFile($uri, $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath("~\.vim\autoload\plug.vim"))
----

.Install Plugins

Open Vim, ignore errors and issue `:PlugInstall!` to install all plugins and themes.

Restart Vim. This time there should be no errors.

.Diff

IMPORTANT: It is possible that diff or Gdiff (in Vim Fugitive) will not work.

Tuxproject Vim does not include a `diff.exe`.

Check output of

----
:!where diff
----

If the result is empty or Gdiff is not working then add `diff.exe` from Git installation to your `%PATH%`.

Open your Environment Variables, edit `%PATH%` to add `C:\Program Files\Git\usr\bin`.

See this https://github.com/tpope/vim-fugitive/issues/680#issuecomment-134650380[Github issue] for details.

=====# Add gVim to Context Menu

I am using portable version of Vim from Tuxproject which does not come with an installer. It does not get added to the Windows context automatically.

To add gVim to context menu, open registry `regedit`.

1. Navigate to `HKEY_CLASSES_ROOT\*\shell`.
1. Add new key under it `gVim`.
1. Change value of `Default` to `Open with gVim`
1. Add a new string value, named `Icon`. Set it's value to gVim executable, in this case `"C:\Users\talha\bin\complete-x64\gvim.exe"`
1. Add a new sub key under `gVim`. Name it `command`
1. Set `command`'s default value to gVim executable, in this case `"C:\Users\talha\bin\complete-x64\gvim.exe" "%1"`

See http://superuser.com/a/37923/42415[this link] for details.

===== AutoHotKey

To auto start the AutoHotKey script every time windows starts. Start `cmd` with administrative privilege in ConEmu. Create symbolic links thusly,

```
mklink "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\init.ahk" %HOMEPATH%\Repos\dotfiles\autohotkey\init.ahk
```

===== Install AutoJump

You must have Clink installed before you install AutoJump

1. Clone https://github.com/wting/autojump[AutoJump]
1. Add https://github.com/wting/autojump/issues/436[patch]
1. Open `cmd`
1. Make sure Clink is working in `cmd`
1. Switch to AutoJump directory
1. Install AutoJump using `python install.py`
1. Successful installation will output a path, add this path your `%PATH%`.

===== Clink

You can view Clink settings and configuration directory using `clink set` command.

=== Color Codes

To have https://github.com/morhetz/gruvbox[Gruvbox] dark theme like background in `cmd` or Git shell, use following color codes:

.Color Codes
[cols="4", options="header"]
|===
|Color Values
|Red
|Green
|Blue

|Screen Background,
|44
|44
|44

|Screen Text
|218
|198
|144
|===

=== Urdu Support

1. Add Urdu language support to Windows 10
1. Install https://urdu.ca/2[Phonetic Keyboard]
1. Install fonts
    1. http://font.urduweb.org/downloads/357-decotype-naskh-regular[DecoType Naskh Regular]
    1. http://font.urduweb.org/downloads/363-diwani-letter-regular[Diwani Letter Regular]
    1. http://font.urduweb.org/downloads/243-khat-e-sulas-regular[Khat-e-Sulas Regular]
    1. http://font.urduweb.org/downloads/244-khat-e-sulas-shipped-regular[Khat-e-Sulas Shipped Regular]
    1. http://font.urduweb.org/downloads/376-old-antic-bold-regular[Old Antic Bold Regular]
    1. http://www.noorehidayat.org/index.php?p=cnt&c=noorehuda.ttf[NooreHuda]
    1. http://font.urduweb.org/downloads/249-jameel-noori-nastaleeq-regular[Jameel Noori Nastaleeq Regular]
    1. https://brushez.com/free_download/10eoM/39610[FS Diwani]

== Outdated Content

CAUTION: I need to review and update following portion of this file.

=== Overview of my dotfiles


These configuration files do not work out of the box. These are specific to my Mac OSX system.

Following are my not so comprehensive and perhaps out of date notes.

=== Git


1.  http://dropshado.ws/post/7844857440/gitconfig-colors[David DeSandro] blog entry is a good start point.
2.  http://cheat.errtheblog.com/s/git[Cheat sheets] has more comprehensive entry.

=== Vim

1.  https://chrome.google.com/webstore/detail/godjoomfiimiddapohpmfklhgmbfffjj[Vrome] is a Google Chrome extension.

===== Auto Close

1.  http://stackoverflow.com/q/883437/177116[SO thread] has got some good comments.
1.  I decided to use Thiago Alves/Townk's https://github.com/Townk/vim-autoclose[plugin].
1.  http://www.vim.org/scripts/script.php?script_id=2009[Townk's plugin tutorial].

===== Vim Markdown

1.  https://github.com/tpope/vim-markdown[tpope/vim-markdown] is mostly used. But it does not conceal text markers in Markdown file.
2.  https://github.com/xolox/vim-markdown[xolox/vim-markdown] does the concealing. See https://github.com/tpope/vim-markdown/pull/9#issuecomment-3098050[this image] for example.
3.  But you have to switch to xolox/vim-markdown `conceal` branch to get his code. Use `git checkout -b conceal remotes/origin/conceal` to
    checkout the branch.

===== Fuzzy File Finder

1.  I tried https://wincent.com/products/command-t/[command-t] but I could not make it work. It requires that your copy of Vim should be compiled with the same version of ruby with which you compiled command-t, which effectively means you have to compile Vim yourself.
2.  I took the easier way, use http://kien.github.com/ctrlp.vim/[CtrlP]. It is basically the same as Command-T but written in pure Vimscript. This means it neither requires Ruby support enabled in Vim nor does it require the compilation of some Ruby extension implemented in C.
3.  Other extensions are either not what I wanted, for example, http://www.vim.org/scripts/script.php?script_id%3D2050[LustyJuggler], or not actively maintained any more like http://www.vim.org/scripts/script.php?script_id%3D1984[FuzzyFinder] and https://github.com/jamis/fuzzy_file_finder[fuzzy file finder].

=== Bash

1.  Bash completion depends on bash\_completion package. MacPorts users can do `sudo port install git-core +bash_completion`.
2.  http://blog.bitfluent.com/post/27983389/git-utilities-you-cant-live-without[Git Utilities You Can't Live Without] blog entry has an entry for Git aware PS1.
