" This section is added for Vundle from [this link](https://github.com/gmarik/vundle/blob/master/README.md#quick-start)
" Begin Vundle section

set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" My Bundles here:
"
" original repos on github
"Bundle 'tpope/vim-fugitive'
"Bundle 'Lokaltog/vim-easymotion'
"Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
"Bundle 'tpope/vim-rails.git'
" vim-scripts repos
"Bundle 'L9'
"Bundle 'FuzzyFinder'
" non github repos
"Bundle 'git://git.wincent.com/command-t.git'
" ...

Bundle 'vimoutliner/vimoutliner'
" to Vim-markdown with conceal support
Bundle 'xolox/vim-markdown'
" to view and change file outline
Bundle 'VOoM'
" to quickly find file in the path and buffers with fuzzy find support
Bundle 'kien/ctrlp.vim'

filetype plugin indent on     " required!
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..

" End Vundle section 

set conceallevel=2
set concealcursor=n

autocmd BufRead,BufNewFile  *.txt,*.TXT set filetype=markdown

if has("gui_running")
  set guifont=Courier_NEW:h11:cANSI
endif
set guifont=Menlo\ Regular:h13
set term=screen-256color
set number
set expandtab
set ruler
set spell
set wrap
syntax on
set autoindent
set softtabstop=4
set shiftwidth=2
set hlsearch
hi clear SpellBad
hi SpellBad cterm=underline, ctermfg=red
hi clear SpellCap
hi SpellCap cterm=underline, ctermfg=green
"set background=dark
"let g:zenburn_alternate_Visual = 1
"colorscheme zenburn 
colorscheme beauty256Talha
set colorcolumn=80

" from [SO answer](http://stackoverflow.com/a/526940/177116)
" When you type the first tab hit will complete as much as possible, the
" second tab hit will provide a list, the third and subsequent tabs will cycle
" through completion options so you can complete the file without further keys
set wildmode=longest,list,full
set wildmenu

" for ctrlp 
let g:ctrlp_map = '<c-x><c-f>'
let g:ctrlp_cmd = 'CtrlP'
nmap <c-x><c-b>  :CtrlPBuffer<CR>

" for :shell, from [SO answer](http://stackoverflow.com/a/12273438/177116)
" Otherwise I get error 
" > __git_ps1: command not found
set shell=bash\ --rcfile\ ~/.bashrc
