(defun talha-emacs-theme ()
  (interactive)
  (color-theme-install
   '(talha-emacs-theme
      ((background-color . "#ffffff")
      (background-mode . light)
      (border-color . "#969696")
      (cursor-color . "#4e564e")
      (foreground-color . "#000000")
      (mouse-color . "black"))
     (fringe ((t (:background "#969696"))))
     (mode-line ((t (:foreground "#f5f5f5" :background "#646262"))))
     (region ((t (:background "#a7a5a5"))))
     (font-lock-builtin-face ((t (:foreground "#203bf8"))))
     (font-lock-comment-face ((t (:foreground "#7d827d"))))
     (font-lock-function-name-face ((t (:foreground "#0621b2"))))
     (font-lock-keyword-face ((t (:foreground "#9c53a2"))))
     (font-lock-string-face ((t (:foreground "#8b490e"))))
     (font-lock-type-face ((t (:foreground"#159899"))))
     (font-lock-constant-face ((t (:foreground "#cf8c02"))))
     (font-lock-variable-name-face ((t (:foreground "#54c738"))))
     (minibuffer-prompt ((t (:foreground "#7299ff" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'talha-emacs-theme)
