windows:
  - name: default
    root: ~/
    layout: even-vertical
    panes:
      - commands:
        - echo "pane 1"
        focus: true  
      - commands:
        - echo "pane 2"
      - commands:
        - xmrig -c ~/Downloads/config.json
      - commands:
        - tiddlysave && tiddlyserver

