windows:
  - name: default
    root: ~/Downloads
    layout: tiled
    panes:
      - commands:
        - echo "pane 1"
        - sleep 10 && exit
      - commands:
        - echo "pane 2"
        focus: true  
      - commands:
        - yt-dlp
      - commands:
        - echo ""

