windows:
  - name: default
    root: ~/Downloads
    layout: tiled
    panes:
      - commands:
        - echo "pane 1"
        - sleep 10 && exit
        focus: true  
      - commands:
        - echo "pane 2"
      - commands:
        - yt-dlp
      - commands:
        - xmrig -c ~/Dropbox/MoneroConfigurations/config-minexmr.com.json
      - commands:
        - tiddlysave && tiddlyserver
      - commands:
        - tiddlysave /Users/talha/Dropbox/TiddlyNotesArchives && tiddlyserver /Users/talha/Dropbox/TiddlyNotesArchives --port 8090

