windows:
  - name: default
    root: ~/
    layout: even-vertical
    panes:
      - commands:
        - echo "pane 1"
        focus: true  
      - commands:
        - echo "pane 2"
      - commands:
        - xmrig -c ~/Dropbox/MoneroConfigurations/config-minexmr.com.json
      - commands:
        - tiddlysave /Users/talha/Dropbox/TiddlyNotesArchives && tiddlyserver /Users/talha/Dropbox/TiddlyNotesArchives --port 8090
      - commands:
        - tiddlysave && tiddlyserver

