# This bash configuration is used on my Mac

set -o vi
set -P # make bash respect physical path

alias ls='ls -GF'
alias grep='grep --color'
alias git='/opt/local/bin/git'
alias vim='/Applications/MacPorts/MacVim.app/Contents/MacOS/Vim'
alias vimdiff='/Applications/MacPorts/MacVim.app/Contents/MacOS/Vim -d'
alias vi='mvim --remote-tab'
alias git-root='if [ "`git rev-parse --show-cdup`" != "" ]; then cd `git rev-parse --show-cdup`; fi'
alias git-forest='git-forest |less -FXRS'

md () { mkdir -p "$@" && cd "$_" ; } 

export PATH=~/bin:$PATH
export EDITOR='/Applications/MacPorts/MacVim.app/Contents/MacOS/Vim'

export PATH=/opt/local/bin:/opt/local/sbin:$PATH
export MANPATH=/opt/local/share/man:$MANPATH

#PS1="[\\u@\\h:\\W]$ "
# to set window tile in screen as the program it is running
#export PS1='\[\033k\033\\\]\u@\h:\w\$ '
#PS1='\[\033k\033\\\][\w]$ '

# Set screen window title
case "$TERM" in
screen)
#linux)
#screen.linux)
#PROMPT_COMMAND='echo -ne "\033k$HOSTNAME\033\\"'
export PROMPT_COMMAND='echo -ne "\033k${PWD##*/}\033\\"'
;;
esac

# To use bash_completion
# make sure you have installed bash_completion
if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
    . /opt/local/etc/profile.d/bash_completion.sh
fi

if [ -f /opt/local/share/git/contrib/completion/git-prompt.sh ]; then
      . /opt/local/share/git/contrib/completion/git-prompt.sh
fi 

PS1='[\w]$(__git_ps1 " (%s) ")\$ '


export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL=

# virtualenvwrapper is a set of extensions to Ian Bicking's virtualenv tool
# http://pypi.python.org/pypi/virtualenvwrapper
export WORKON_HOME=~/Repos/VirtualEnvs
export VIRTUALENVWRAPPER_HOOK_DIR=~/Repos/VirtualEnvWrapper_Hooks


if [ ! -d "$WORKON_HOME" ] ; then
  mkdir -p "$WORKON_HOME"
fi

if [ ! -d "$VIRTUALENVWRAPPER_HOOK_DIR" ] ; then
  mkdir -p "$VIRTUALENVWRAPPER_HOOK_DIR"
fi

if [ -f /usr/local/bin/virtualenvwrapper.sh ] ; then
  source /usr/local/bin/virtualenvwrapper.sh
fi

export HISTCONTROL=ignorespace 
function gi() { curl http://www.gitignore.io/api/$@ ;}

shopt -s cdspell
shopt -s dirspell

# To use autojump for bash
if [ -f /opt/local/etc/profile.d/autojump.bash ]; then
    . /opt/local/etc/profile.d/autojump.bash
fi

